spring.application.name = APPLICATION_NAME
spring.datasource.username = USERNAME
spring.datasource.password = PASSWORD
spring.datasource.url = URL
spring.jpa.properties.hibernate.dialect = DIALECT
spring.jpa.show_sql = true